<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_DeletedCitation extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'deleted_citation', array('workflow_id','faculty_eid','created_by','edited_by','sort_order','text','revised_text','year','annotation_text','is_peer','is_creative','is_pending','timestamp','section_header','section_id','version_id','reviewed'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getWorkflow_id() { return $this->fields["workflow_id"]; }
    public function getFaculty_eid() { return $this->fields["faculty_eid"]; }
    public function getCreated_by() { return $this->fields["created_by"]; }
    public function getEdited_by() { return $this->fields["edited_by"]; }
    public function getSort_order() { return $this->fields["sort_order"]; }
    public function getText() { return $this->fields["text"]; }
    public function getRevised_text() { return $this->fields["revised_text"]; }
    public function getYear() { return $this->fields["year"]; }
    public function getAnnotation_text() { return $this->fields["annotation_text"]; }
    public function getIs_peer() { return $this->fields["is_peer"]; }
    public function getIs_creative() { return $this->fields["is_creative"]; }
    public function getIs_pending() { return $this->fields["is_pending"]; }
    public function getTimestamp() { return $this->fields["timestamp"]; }
    public function getSection_header() { return $this->fields["section_header"]; }
    public function getSection_id() { return $this->fields["section_id"]; }
    public function getVersion_id() { return $this->fields["version_id"]; }
    public function getReviewed() { return $this->fields["reviewed"]; }
}