<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_FacultySectionHeader extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'faculty_section_header', array('faculty_eid','text','version','sort_order'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getFaculty_eid() { return $this->fields["faculty_eid"]; }
    public function getText() { return $this->fields["text"]; }
    public function getVersion() { return $this->fields["version"]; }
    public function getSort_order() { return $this->fields["sort_order"]; }
}