<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_FacultyProxy extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'faculty_proxy', array('faculty_eid','proxy_eid','proxy_name','created','created_by'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getFaculty_eid() { return $this->fields["faculty_eid"]; }
    public function getProxy_eid() { return $this->fields["proxy_eid"]; }
    public function getProxy_name() { return $this->fields["proxy_name"]; }
    public function getCreated() { return $this->fields["created"]; }
    public function getCreated_by() { return $this->fields["created_by"]; }
}