<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Faculty extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'faculty', array('eid','certified_citations','tenure','dept','college','citation_count','retrieved_from_ted','uid','utexasedupersoneid','utexasedupersonprioreid','utexasedupersonpermeid','displayname','utexasedupersonaffiliation','edupersonprimaryaffiliation','utexasedupersonflsaexemptsw','utexasedupersonfullparttimeemployee','utexasedupersonhighestdegree','utexasedupersonjobclasscategorycode','utexasedupersonjobclasscode','mail','utexasedupersonorgunitname','utexasedupersonprimaryorgunitname','cn','sn','givenname','utexasedupersonprimarytitle','created','created_by'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getEid() { return $this->fields["eid"]; }
    public function getCertified_citations() { return $this->fields["certified_citations"]; }
    public function getTenure() { return $this->fields["tenure"]; }
    public function getDept() { return $this->fields["dept"]; }
    public function getCollege() { return $this->fields["college"]; }
    public function getCitation_count() { return $this->fields["citation_count"]; }
    public function getRetrieved_from_ted() { return $this->fields["retrieved_from_ted"]; }
    public function getUid() { return $this->fields["uid"]; }
    public function getUtexasedupersoneid() { return $this->fields["utexasedupersoneid"]; }
    public function getUtexasedupersonprioreid() { return $this->fields["utexasedupersonprioreid"]; }
    public function getUtexasedupersonpermeid() { return $this->fields["utexasedupersonpermeid"]; }
    public function getDisplayname() { return $this->fields["displayname"]; }
    public function getUtexasedupersonaffiliation() { return $this->fields["utexasedupersonaffiliation"]; }
    public function getEdupersonprimaryaffiliation() { return $this->fields["edupersonprimaryaffiliation"]; }
    public function getUtexasedupersonflsaexemptsw() { return $this->fields["utexasedupersonflsaexemptsw"]; }
    public function getUtexasedupersonfullparttimeemployee() { return $this->fields["utexasedupersonfullparttimeemployee"]; }
    public function getUtexasedupersonhighestdegree() { return $this->fields["utexasedupersonhighestdegree"]; }
    public function getUtexasedupersonjobclasscategorycode() { return $this->fields["utexasedupersonjobclasscategorycode"]; }
    public function getUtexasedupersonjobclasscode() { return $this->fields["utexasedupersonjobclasscode"]; }
    public function getMail() { return $this->fields["mail"]; }
    public function getUtexasedupersonorgunitname() { return $this->fields["utexasedupersonorgunitname"]; }
    public function getUtexasedupersonprimaryorgunitname() { return $this->fields["utexasedupersonprimaryorgunitname"]; }
    public function getCn() { return $this->fields["cn"]; }
    public function getSn() { return $this->fields["sn"]; }
    public function getGivenname() { return $this->fields["givenname"]; }
    public function getUtexasedupersonprimarytitle() { return $this->fields["utexasedupersonprimarytitle"]; }
    public function getCreated() { return $this->fields["created"]; }
    public function getCreated_by() { return $this->fields["created_by"]; }
}