<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_UploadedFile extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'uploaded_file', array('name','orig_name','faculty_eid','uploaded','upload_mime','upload_note','uploaded_by','date_on_cv','other_updated','status','note','rawtext','rawtext_size','rawtext_md5','converted','workflow_state','edited_text'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getName() { return $this->fields["name"]; }
    public function getOrig_name() { return $this->fields["orig_name"]; }
    public function getFaculty_eid() { return $this->fields["faculty_eid"]; }
    public function getUploaded() { return $this->fields["uploaded"]; }
    public function getUpload_mime() { return $this->fields["upload_mime"]; }
    public function getUpload_note() { return $this->fields["upload_note"]; }
    public function getUploaded_by() { return $this->fields["uploaded_by"]; }
    public function getDate_on_cv() { return $this->fields["date_on_cv"]; }
    public function getOther_updated() { return $this->fields["other_updated"]; }
    public function getStatus() { return $this->fields["status"]; }
    public function getNote() { return $this->fields["note"]; }
    public function getRawtext() { return $this->fields["rawtext"]; }
    public function getRawtext_size() { return $this->fields["rawtext_size"]; }
    public function getRawtext_md5() { return $this->fields["rawtext_md5"]; }
    public function getConverted() { return $this->fields["converted"]; }
    public function getWorkflow_state() { return $this->fields["workflow_state"]; }
    public function getEdited_text() { return $this->fields["edited_text"]; }
}